### ISSUE TITLE
kendo grid export to pdf

### ISSUE THREAD

**Issue by mahikkp** [M-Yankov/UniversityStudentSystem#11]
Hi Team,
I am looking for kendo grid export to PDF. I already implemented the below logic but the after click on Export to PDF only showing first page in PDF. Can you please check what ia m missing?
$("#GridLogs").kendoGrid({
           
        toolbar: ["pdf"],
        pdf: {
            fileName: todayDate + "   " + "Error.pdf",
            allPages: true
            
        },

![11-10-2016 4-24-22 pm](https://cloud.githubusercontent.com/assets/20096086/20199866/656d4e1a-a762-11e6-8302-4988bb1ecace.jpg)

**Comment by M-Yankov** [comment]
Hi,
I am not familiar with your server implementation. As I can see there is another option for exporting `PDF`

``` html
<button id="export">Export to PDF</button>
<div id="grid"></div>
<script>
$("#grid").kendoGrid({
  columns: [
    { field: "name" },
    { field: "age" }
  ],
  dataSource: [
      { name: "Jane Doe", age: 30 },
      { name: "John Doe", age: 33 }
  ],
});
$("#export").click(function(e) {
    var grid = $("#grid").data("kendoGrid");
    grid.saveAsPDF();
});
</script>
```

You can see the example at this [Link](http://docs.telerik.com/kendo-ui/api/javascript/ui/grid#methods-saveAsPDF).
If you could provide more information about data source and other kendo config options, I can assist.
